---
steps:
  - label: ":hammer: build"
    command: .buildkite/pipeline.exec.sh
    concurrency: 1
    concurrency_group: primary
    timeout_in_minutes: 45
    branches: master
    env:
      - BUILDKITE_CLEAN_CHECKOUT: true
    agents:
      os: linux

  - wait

  - label: ":radioactive_sign: teardown"
    command: .buildkite/pipeline.teardown.sh
    branches: master
    env:
      - BUILDKITE_CLEAN_CHECKOUT: true
    agents:
      os: linux
